version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/London
  open-pull-requests-limit: 30
  versioning-strategy: increase
  ignore:
  - dependency-name: "*"
    update-types: ["version-update:semver-patch"]
  groups:
    typescript-eslint:
      applies-to: version-updates
      patterns:
      - "@typescript-eslint/*"
    jest:
      applies-to: version-updates
      patterns:
      - "@types/jest"
      - "jest"
      - "jest-environment-jsdom"
      - "ts-jest"
