#!/usr/bin/env bash

set -eu

cwd="$(cd "$(dirname "$0")" && pwd)"

fly --target ci \
    set-pipeline \
    --pipeline boclips-player-react \
    --config "$cwd/pipeline.yml" \
    --var npm-username="$(lpass show npmjs --username)" \
    --var npm-password="$(lpass show npmjs --password)" \
    --var github-access-token="$(lpass show boclips-player-react-github-access-token --notes)"
